P_sat: 0.003
alpha: 2.5
beta: 0.0001
chi_e: 0.007
cs2: 0.5
train_size: 100
train_pearson_r: 0.7208
train_spearman_rho: 0.7315
train_rmse: 2.8360
train_mae: 2.2380
test_size: 128
test_pearson_r: 0.7355
test_spearman_rho: 0.7468
test_rmse: 2.8663
test_mae: 2.3119
clean_test_size: 126
clean_test_pearson_r: 0.7736
clean_test_spearman_rho: 0.7642
clean_test_rmse: 2.7487
clean_test_mae: 2.2367
